apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: app2
  name: app2
  namespace: mphasis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: app2
    spec:
      containers:
      - image: kharatramesh/mphasis:mphasisv1.0
        name: mphasis
        resources:
          requests:
            cpu: 20m
            memory: 20Mi
          limits:
            cpu: 30m
            memory: 40Mi
